// @generated by scripts/generate-migration-manifest.mjs — DO NOT EDIT BY HAND.
// Regenerate with: node scripts/generate-migration-manifest.mjs
//
// The complete, mechanically-derived set of migrations that define the production
// release head. This is the deterministic replacement for the hand-curated
// `expected_migrations` table (PTM-OBS-012), so migration parity can never again
// report green while security-critical migrations are missing from production.

export type MigrationManifestEntry = {
  version: string;
  file: string;
  checksum: string;
};

export const REQUIRED_MIGRATIONS: readonly MigrationManifestEntry[] = [
  {
    "version": "202605290001",
    "file": "202605290001_init.sql",
    "checksum": "680af588105e66d416c45b55a49c0b442d3454fd9e9b25881eae97fab1a97857"
  },
  {
    "version": "202605300001",
    "file": "202605300001_v2_phase_a_backbone.sql",
    "checksum": "8d48a7fe0e40b832144661b508c20f8b9734ac804c3a774aa0b52c99ea2a56f5"
  },
  {
    "version": "202605300002",
    "file": "202605300002_v2_phase_b_ops.sql",
    "checksum": "0af70e0f9756ab93c1b0e990ed4d3aa7680b40687677c1a27104ba4731a8a100"
  },
  {
    "version": "202605300003",
    "file": "202605300003_v2_phase_c_admin_products.sql",
    "checksum": "a444856fca53b77826614e77dffa29911615f5335103ae284c2da0f07a7bab70"
  },
  {
    "version": "202605300004",
    "file": "202605300004_v2_phase_d_admin_ops.sql",
    "checksum": "93d987dd953e2725440684c7766164f2aa9dcf83b4efc776cacd9ab564a86eca"
  },
  {
    "version": "202605310001",
    "file": "202605310001_v2_phase_e_sms_test_mode.sql",
    "checksum": "0a97c4ce5eef13a4b427d47ef748bc07b3a6a4b383f122936b93fa9f624da459"
  },
  {
    "version": "202605310002",
    "file": "202605310002_v2_phase_e_customer_cancel.sql",
    "checksum": "0180bb6c286b9231817c735cb07344e783c7b529ae068b4219791d5c77432607"
  },
  {
    "version": "202605310003",
    "file": "202605310003_v2_1_compliance_inventory.sql",
    "checksum": "2aa5f89c41c6e7fd9bfd7583bc7a4256bae5add41d10f15c7ccb02f3f4fad0e5"
  },
  {
    "version": "202606011430",
    "file": "202606011430_v3_operational_system.sql",
    "checksum": "086b27a1de4e03ff780f370dbd38db7de88faf7b59e7edcaba35d50be0e7e695"
  },
  {
    "version": "202606011900",
    "file": "202606011900_v4_operations_intelligence.sql",
    "checksum": "a27abe7a955a0365981a11ed325378e958e86ed33b5bda3d0a7fca748b024b6d"
  },
  {
    "version": "202606012030",
    "file": "202606012030_v5_action_intelligence.sql",
    "checksum": "3832c03f0cedb886372b9bc115e4a1e697f6af0ac544b7d795191f49c34eb98c"
  },
  {
    "version": "202606021000",
    "file": "202606021000_v6_product_cost.sql",
    "checksum": "6eb305a9ca97bed076a029634f90131af1cfebeff73ac71e91a4bd49ef933a5b"
  },
  {
    "version": "202606021100",
    "file": "202606021100_v6_4_carcass_intake.sql",
    "checksum": "2069e3c259a4bbd5163312fcaa12563534589d5489cdbd77b9e8f9bef7943dc4"
  },
  {
    "version": "202606021500",
    "file": "202606021500_v6_5_inventory_integrity.sql",
    "checksum": "e0a6879973c68eddce75749770a166c0b2482ef3d8767ced156eb255ce8d33f3"
  },
  {
    "version": "202606031000",
    "file": "202606031000_v6_6_inventory_reality.sql",
    "checksum": "f2cbfd7a83c908334de10294e3d77a7a01e1523869979afcee38a7a70a46f428"
  },
  {
    "version": "202606041700",
    "file": "202606041700_v10_phase2_guided_capture.sql",
    "checksum": "bff9954036ffa585b586ad84e664784389317018550a8c2336569c2e79d6f010"
  },
  {
    "version": "202606051200",
    "file": "202606051200_v11_1_public_order_access.sql",
    "checksum": "bcf02bc8fa5815183a082812a6cd4dc678a5fa43efe072db7131081e4839169b"
  },
  {
    "version": "202606051300",
    "file": "202606051300_v11_1_seal_public_access.sql",
    "checksum": "a29c2dce2d265273dee63fdef40945c611ce892f4831c39e848ebc09095fde0e"
  },
  {
    "version": "202606051400",
    "file": "202606051400_v11_2_audit_authenticity.sql",
    "checksum": "8ff4c1d9398116f09e996a7e403a6762a67174911350574946b98ae0d6208393"
  },
  {
    "version": "202606061200",
    "file": "202606061200_v12_1_rpc_authority_seal.sql",
    "checksum": "f836332884db4f81c6eb9b28e9517beb1eead0137e5da9039c3eb5e76263a6af"
  },
  {
    "version": "202606071000",
    "file": "202606071000_v12_3_checkout_integrity.sql",
    "checksum": "650adc018cb4cb559ff3173b632b565fa4a9a198a5130569cdc0d15c119b633d"
  },
  {
    "version": "202606071600",
    "file": "202606071600_v12_5_inventory_stale_count_guard.sql",
    "checksum": "05fc733c3a5798ef44a23048d8727fb18833f1b8dbcfdc140c6ed03e8f6cf985"
  },
  {
    "version": "202606071700",
    "file": "202606071700_v12_6_checklist_evidence_integrity.sql",
    "checksum": "5fa5f950d8d28c0050b0c5104e24f16a3a6556c2d68e7d3b06bff012f68b5cde"
  },
  {
    "version": "202606071800",
    "file": "202606071800_compliance_temperature_capture.sql",
    "checksum": "1091480a21f486af04e5846b704ea6275531842b5a47ac742dd793921d4b28cc"
  },
  {
    "version": "202606081000",
    "file": "202606081000_v13_1_pricing_validation.sql",
    "checksum": "a23084956f547bbac0b78414b01818ceb4b3797929fc1bb72f6f196aed3414ea"
  },
  {
    "version": "202606081100",
    "file": "202606081100_v13_2_disaster_recovery.sql",
    "checksum": "456a64b329e865c2a6939159c4f3d472de18ca3fcf70aa8e84ebcc74d2ddd2e7"
  },
  {
    "version": "202606082000",
    "file": "202606082000_v14_1_sales_stock_truth.sql",
    "checksum": "12803022a997fd78504b005e718aa43b9f626781e2358867cff539ad3cacd02d"
  },
  {
    "version": "202606090900",
    "file": "202606090900_v14_1_h_inventory_truth_hardening.sql",
    "checksum": "194d0c7b748e96246bcdcbec50bdf71be5e68ea241bf09dc14e22a7557d3c7ce"
  },
  {
    "version": "202606091000",
    "file": "202606091000_v14_1_h_reassert_sale_depletion_hook.sql",
    "checksum": "f613b31ffad29f54456faa74d43bea2d9d530347a9c5052980b50232b87a5cc6"
  },
  {
    "version": "202606111200",
    "file": "202606111200_v17_operator_mode.sql",
    "checksum": "915b339830def8988e7e7097e9c2ad19c9b610063adcbb274afda1507ef51d22"
  },
  {
    "version": "202606121000",
    "file": "202606121000_v17_3_evidence_capture.sql",
    "checksum": "27b0caf05649d9ab43bb6b07ac237b0985bfc425826fda8a32cc2d6f396736fd"
  },
  {
    "version": "202606290900",
    "file": "202606290900_phase0_lock_truth_tables.sql",
    "checksum": "9b572ec9629bd8461a0597f087df71bcd2162adbbf9494bc111f0d11658e62e0"
  },
  {
    "version": "202606291000",
    "file": "202606291000_phase1_required_compliance_evidence.sql",
    "checksum": "7db9d9e1ae9e156e673476a4d45996afa3df6a5e4846476cc45b9fd9c97cac66"
  },
  {
    "version": "202606291100",
    "file": "202606291100_phase2_drop_phantom_counter_customer.sql",
    "checksum": "98405873e031b2486ff99b5bae5287c7670e20674d3c776257d1907b8aba30a3"
  },
  {
    "version": "202606300900",
    "file": "202606300900_v17_8_reconcile_delivery_cost.sql",
    "checksum": "2335dc82095785eb152cfab6a35840d3b6165f4635be67e597b4cdef6eaeb61f"
  },
  {
    "version": "202606301000",
    "file": "202606301000_clean_local_api_grants.sql",
    "checksum": "978ea49ab536c03cf9352063c4c251ffe59b9e3599bea6f796ce2678608a008c"
  },
  {
    "version": "202607011300",
    "file": "202607011300_service_role_api_grants.sql",
    "checksum": "d07cbe1580fd8ee989b85a6ae417890ca0608dad4a3bc907761c1cfaa7c6039f"
  },
  {
    "version": "202607101200",
    "file": "202607101200_phase3_lock_products_and_events.sql",
    "checksum": "28557d2a10e1662b1f086a54056baa66516ad895472808f847dd696009da4953"
  },
  {
    "version": "202607110900",
    "file": "202607110900_revoke_next_order_ref_anon.sql",
    "checksum": "727d4bfe6678947faac85e126122684f162bb3e26e8198ea7bd82bc6f4ab2b01"
  },
  {
    "version": "202607111000",
    "file": "202607111000_ops_backup_ledger.sql",
    "checksum": "e9ff4ded4738edb6c80024a79804fe04ce6c69c8c712b93ab74aab3dfb4dde60"
  },
  {
    "version": "202607111100",
    "file": "202607111100_shortfall_owner_alert.sql",
    "checksum": "2859e40fe5dff241e0e42dbda80ffe273da0ec5c4b7af6c21a50e367422c6f5f"
  },
  {
    "version": "202607141000",
    "file": "202607141000_v18_payment_truth.sql",
    "checksum": "7572c87e510520c9f7c51e4e47f8d020c1e85b94bcc073d638b49c98b7f8f0ef"
  },
  {
    "version": "202607141100",
    "file": "202607141100_v18_close_money_steps.sql",
    "checksum": "502249aed323d086a1073b4a33e54eaac2a92bcb7206ca24959b14839c0135f1"
  },
  {
    "version": "202607141200",
    "file": "202607141200_v18_audit_vocabulary.sql",
    "checksum": "9077034acf4d9cba00c8d19dc06155ca7e72214d2d09f23efaf73eab5f799136"
  },
  {
    "version": "202607141300",
    "file": "202607141300_v18_inventory_policy.sql",
    "checksum": "9ee85d8e3fd4d60d7452125b26eb9f19ec38320d75181534a492ef2fda4b57fe"
  },
  {
    "version": "202607141400",
    "file": "202607141400_v18_alert_dispatch.sql",
    "checksum": "9058cf9c58702fa8409d532bc3a4f99b0fb36bd274fb8cf3b0a1e3d056aad929"
  },
  {
    "version": "202607141500",
    "file": "202607141500_v18_alert_lifecycle.sql",
    "checksum": "4c4668b3bf1635778212582c4860bb873ce60712b04999f7ad6e420cdb248102"
  },
  {
    "version": "202607141600",
    "file": "202607141600_v18_refunds.sql",
    "checksum": "c4db4c751ee47d16066d4545575990fb8bb7227bcd57d341db54e43048925c4d"
  },
  {
    "version": "202607141700",
    "file": "202607141700_v18_order_amendments.sql",
    "checksum": "66cf8755ae16a4490dde136461134b499f1d4195a276017983c92c1437b199e3"
  },
  {
    "version": "202607142100",
    "file": "202607142100_v18_certificate_expiry_alerts.sql",
    "checksum": "cfdba527368538a8b2562dd58343d142eb114fda080eba68109c765cab09fc2a"
  },
  {
    "version": "202607142200",
    "file": "202607142200_v18_atomic_operator_serve.sql",
    "checksum": "d4fef6f15a5f6f39d0ccdc37ee8d93ebd2236c3212221db7346ce6ddc5823e83"
  },
  {
    "version": "202607142300",
    "file": "202607142300_v18_operator_run_completion.sql",
    "checksum": "c711d235cc19ce4d7a9987e8e6bc4ffb06cab6220c29cd4153f9f24d96eecc7c"
  },
  {
    "version": "202607142400",
    "file": "202607142400_v18_atomic_evidence_finalize.sql",
    "checksum": "c1bad18ad64a50a1a80b7195465c3cf83692f06a849207cba12ef0f089ddabc5"
  },
  {
    "version": "202607150900",
    "file": "202607150900_v18_edge_dispatcher.sql",
    "checksum": "3d4d1b64056d63643d7f476ee6e9820a240ef526846994c3b9d76c539a722923"
  },
  {
    "version": "202607151500",
    "file": "202607151500_v18_web_push.sql",
    "checksum": "12066c706fc025b0d53d7a94fc8bc989267d2aa7d4bbcc1e2adaba7e7be3bd83"
  },
  {
    "version": "202607152315",
    "file": "202607152315_v18_phase35_web_push_field_fixes.sql",
    "checksum": "26e11572fb9a482f48fb5ba9fab7952c083c04bac7f5948b86da6f1f603fe512"
  },
  {
    "version": "202607161505",
    "file": "202607161505_v18_phase35_accepted_dispatch_replay.sql",
    "checksum": "360fb9e8c0df8d607b75d80bbc8fffac25f502eae8328733ed971fcc67cf9ecf"
  }
] as const;

export const REQUIRED_MIGRATION_VERSIONS: readonly string[] = [
  "202605290001",
  "202605300001",
  "202605300002",
  "202605300003",
  "202605300004",
  "202605310001",
  "202605310002",
  "202605310003",
  "202606011430",
  "202606011900",
  "202606012030",
  "202606021000",
  "202606021100",
  "202606021500",
  "202606031000",
  "202606041700",
  "202606051200",
  "202606051300",
  "202606051400",
  "202606061200",
  "202606071000",
  "202606071600",
  "202606071700",
  "202606071800",
  "202606081000",
  "202606081100",
  "202606082000",
  "202606090900",
  "202606091000",
  "202606111200",
  "202606121000",
  "202606290900",
  "202606291000",
  "202606291100",
  "202606300900",
  "202606301000",
  "202607011300",
  "202607101200",
  "202607110900",
  "202607111000",
  "202607111100",
  "202607141000",
  "202607141100",
  "202607141200",
  "202607141300",
  "202607141400",
  "202607141500",
  "202607141600",
  "202607141700",
  "202607142100",
  "202607142200",
  "202607142300",
  "202607142400",
  "202607150900",
  "202607151500",
  "202607152315",
  "202607161505"
] as const;

export const REQUIRED_MIGRATION_HEAD = "202607161505" as const;

export const MIGRATION_MANIFEST_CHECKSUM = "a2eb356e3db75af52baade4f836566047e15ea49a94df3ad8a2d041f417639bf" as const;

export const REQUIRED_MIGRATION_COUNT = 57 as const;
