// @generated by scripts/generate-migration-manifest.mjs — DO NOT EDIT BY HAND.
// Regenerate with: node scripts/generate-migration-manifest.mjs
//
// The complete, mechanically-derived set of migrations that define the production
// release head. This is the deterministic replacement for the hand-curated
// `expected_migrations` table (PTM-OBS-012), so migration parity can never again
// report green while security-critical migrations are missing from production.

export type MigrationManifestEntry = {
  version: string;
  file: string;
  checksum: string;
};

export const REQUIRED_MIGRATIONS: readonly MigrationManifestEntry[] = [
  {
    "version": "202605290001",
    "file": "202605290001_init.sql",
    "checksum": "9ce1e8f4dba47f6d35556c61d90291e6a9efdd3f43d5b05f98c1e6b2030cb625"
  },
  {
    "version": "202605300001",
    "file": "202605300001_v2_phase_a_backbone.sql",
    "checksum": "8d48a7fe0e40b832144661b508c20f8b9734ac804c3a774aa0b52c99ea2a56f5"
  },
  {
    "version": "202605300002",
    "file": "202605300002_v2_phase_b_ops.sql",
    "checksum": "0af70e0f9756ab93c1b0e990ed4d3aa7680b40687677c1a27104ba4731a8a100"
  },
  {
    "version": "202605300003",
    "file": "202605300003_v2_phase_c_admin_products.sql",
    "checksum": "a444856fca53b77826614e77dffa29911615f5335103ae284c2da0f07a7bab70"
  },
  {
    "version": "202605300004",
    "file": "202605300004_v2_phase_d_admin_ops.sql",
    "checksum": "93d987dd953e2725440684c7766164f2aa9dcf83b4efc776cacd9ab564a86eca"
  },
  {
    "version": "202605310001",
    "file": "202605310001_v2_phase_e_sms_test_mode.sql",
    "checksum": "0a97c4ce5eef13a4b427d47ef748bc07b3a6a4b383f122936b93fa9f624da459"
  },
  {
    "version": "202605310002",
    "file": "202605310002_v2_phase_e_customer_cancel.sql",
    "checksum": "0180bb6c286b9231817c735cb07344e783c7b529ae068b4219791d5c77432607"
  },
  {
    "version": "202605310003",
    "file": "202605310003_v2_1_compliance_inventory.sql",
    "checksum": "2aa5f89c41c6e7fd9bfd7583bc7a4256bae5add41d10f15c7ccb02f3f4fad0e5"
  },
  {
    "version": "202606011430",
    "file": "202606011430_v3_operational_system.sql",
    "checksum": "086b27a1de4e03ff780f370dbd38db7de88faf7b59e7edcaba35d50be0e7e695"
  },
  {
    "version": "202606011900",
    "file": "202606011900_v4_operations_intelligence.sql",
    "checksum": "a27abe7a955a0365981a11ed325378e958e86ed33b5bda3d0a7fca748b024b6d"
  },
  {
    "version": "202606012030",
    "file": "202606012030_v5_action_intelligence.sql",
    "checksum": "3832c03f0cedb886372b9bc115e4a1e697f6af0ac544b7d795191f49c34eb98c"
  },
  {
    "version": "202606021000",
    "file": "202606021000_v6_product_cost.sql",
    "checksum": "845d49c3cd744dc242aa2a32dab0e666ef54d29b449d4643f6e3bad8f4eeb959"
  },
  {
    "version": "202606021100",
    "file": "202606021100_v6_4_carcass_intake.sql",
    "checksum": "6677e01b37477b84ab8769c0ee34947edb52261fd7f016279cc0fe5d053f0982"
  },
  {
    "version": "202606021500",
    "file": "202606021500_v6_5_inventory_integrity.sql",
    "checksum": "e0a6879973c68eddce75749770a166c0b2482ef3d8767ced156eb255ce8d33f3"
  },
  {
    "version": "202606031000",
    "file": "202606031000_v6_6_inventory_reality.sql",
    "checksum": "f2cbfd7a83c908334de10294e3d77a7a01e1523869979afcee38a7a70a46f428"
  },
  {
    "version": "202606041700",
    "file": "202606041700_v10_phase2_guided_capture.sql",
    "checksum": "25c14e0589d5622489b68fe3bc9bbbc91f3b86ff72e7c1c773a30eae36861d71"
  },
  {
    "version": "202606051200",
    "file": "202606051200_v11_1_public_order_access.sql",
    "checksum": "e4296174a7a49163f43f8ff9340071786eefbdb9aae23c5f1ba1c462231591cd"
  },
  {
    "version": "202606051300",
    "file": "202606051300_v11_1_seal_public_access.sql",
    "checksum": "cbac4b02b5b2096770d94a1dca74fc40c002845966fe84e9199532074082a3d1"
  },
  {
    "version": "202606051400",
    "file": "202606051400_v11_2_audit_authenticity.sql",
    "checksum": "d2568ffbbce24d0e44a44e0533326bef9a4a9c54ea3171857cb908949fd29830"
  },
  {
    "version": "202606061200",
    "file": "202606061200_v12_1_rpc_authority_seal.sql",
    "checksum": "f836332884db4f81c6eb9b28e9517beb1eead0137e5da9039c3eb5e76263a6af"
  },
  {
    "version": "202606071000",
    "file": "202606071000_v12_3_checkout_integrity.sql",
    "checksum": "998b1bf98c69f3aee34d0a651b34397017b9acf90771d01a1b0e7255432f7a18"
  },
  {
    "version": "202606071600",
    "file": "202606071600_v12_5_inventory_stale_count_guard.sql",
    "checksum": "695ee7785973c7d701c0769e1bab4bf808730ee893e9163c810c8d24f5f8cbf8"
  },
  {
    "version": "202606071700",
    "file": "202606071700_v12_6_checklist_evidence_integrity.sql",
    "checksum": "834dd75b568cfff4b74545aabe1c4748c05b3f348824e8447a23e9051460f660"
  },
  {
    "version": "202606071800",
    "file": "202606071800_compliance_temperature_capture.sql",
    "checksum": "d6246aaa74db75922403e003797505a023fd6d0e7daca06ca165a37df2d2b828"
  },
  {
    "version": "202606081000",
    "file": "202606081000_v13_1_pricing_validation.sql",
    "checksum": "dd606fbc967e7fa124e3b2fad41c10fbd94a97d1a14c40615f745c49c1057359"
  },
  {
    "version": "202606081100",
    "file": "202606081100_v13_2_disaster_recovery.sql",
    "checksum": "26064cf0d42b4123146f4765e2eb1b0eb23a46440e17905da2d759f59328e7a8"
  },
  {
    "version": "202606082000",
    "file": "202606082000_v14_1_sales_stock_truth.sql",
    "checksum": "73dd2d84a8c4ac42774d16060325f59383bafc3ed799c9c7d93b2b97608370fe"
  },
  {
    "version": "202606090900",
    "file": "202606090900_v14_1_h_inventory_truth_hardening.sql",
    "checksum": "8d39911213c52b8ff4de4cdb4a1b1635a2d53d8c8c8e3fdb6f5e6a17b84dc12b"
  },
  {
    "version": "202606091000",
    "file": "202606091000_v14_1_h_reassert_sale_depletion_hook.sql",
    "checksum": "787ea1b525d9eb073f76df3c8481fb97812ff74b7e343170e01cfb51da420b30"
  },
  {
    "version": "202606111200",
    "file": "202606111200_v17_operator_mode.sql",
    "checksum": "915b339830def8988e7e7097e9c2ad19c9b610063adcbb274afda1507ef51d22"
  },
  {
    "version": "202606121000",
    "file": "202606121000_v17_3_evidence_capture.sql",
    "checksum": "27b0caf05649d9ab43bb6b07ac237b0985bfc425826fda8a32cc2d6f396736fd"
  },
  {
    "version": "202606290900",
    "file": "202606290900_phase0_lock_truth_tables.sql",
    "checksum": "2232cfa1e85eba71aded03cdb9f0788f2e7958649c5749f25ccde8c0ea34ed93"
  },
  {
    "version": "202606291000",
    "file": "202606291000_phase1_required_compliance_evidence.sql",
    "checksum": "dcd87092b1940cdf270df02a4c5b633c877a6227d2b15e7b2cd6a7fc14a10bbb"
  },
  {
    "version": "202606291100",
    "file": "202606291100_phase2_drop_phantom_counter_customer.sql",
    "checksum": "0fc0750da4cf8f6ae60d539a506e420bbee98c67439ea84db04fab2cd357a602"
  },
  {
    "version": "202606300900",
    "file": "202606300900_v17_8_reconcile_delivery_cost.sql",
    "checksum": "9ff6631ef24b3b2faf90a49ba98c7922f21ea71cb9917b962127d29f35336e71"
  },
  {
    "version": "202606301000",
    "file": "202606301000_clean_local_api_grants.sql",
    "checksum": "36bcff99ec12ba74452433d55e9d25908b131ef0b466bb7d9d2a625a52fd5e38"
  },
  {
    "version": "202607011300",
    "file": "202607011300_service_role_api_grants.sql",
    "checksum": "d78bbec7fb02f3ba01868defd38d52a32697ed275195df5b16cd3385cbb396b2"
  },
  {
    "version": "202607101200",
    "file": "202607101200_phase3_lock_products_and_events.sql",
    "checksum": "28557d2a10e1662b1f086a54056baa66516ad895472808f847dd696009da4953"
  },
  {
    "version": "202607110900",
    "file": "202607110900_revoke_next_order_ref_anon.sql",
    "checksum": "727d4bfe6678947faac85e126122684f162bb3e26e8198ea7bd82bc6f4ab2b01"
  },
  {
    "version": "202607111000",
    "file": "202607111000_ops_backup_ledger.sql",
    "checksum": "e9ff4ded4738edb6c80024a79804fe04ce6c69c8c712b93ab74aab3dfb4dde60"
  }
] as const;

export const REQUIRED_MIGRATION_VERSIONS: readonly string[] = [
  "202605290001",
  "202605300001",
  "202605300002",
  "202605300003",
  "202605300004",
  "202605310001",
  "202605310002",
  "202605310003",
  "202606011430",
  "202606011900",
  "202606012030",
  "202606021000",
  "202606021100",
  "202606021500",
  "202606031000",
  "202606041700",
  "202606051200",
  "202606051300",
  "202606051400",
  "202606061200",
  "202606071000",
  "202606071600",
  "202606071700",
  "202606071800",
  "202606081000",
  "202606081100",
  "202606082000",
  "202606090900",
  "202606091000",
  "202606111200",
  "202606121000",
  "202606290900",
  "202606291000",
  "202606291100",
  "202606300900",
  "202606301000",
  "202607011300",
  "202607101200",
  "202607110900",
  "202607111000"
] as const;

export const REQUIRED_MIGRATION_HEAD = "202607111000" as const;

export const MIGRATION_MANIFEST_CHECKSUM = "18aa72a6e4d5202c4ddb2b3d33a1bed189df8716c95d4c8833da0a10d39ae917" as const;

export const REQUIRED_MIGRATION_COUNT = 40 as const;
