import type { TutorialStep } from "./types";

export const completeShopDaySteps: readonly TutorialStep[] = [
  { id: "intro", route: "/operator", target: null, titleKey: "dryRun.intro.title", instructionKey: "dryRun.intro.instruction" },
  { id: "open.navigate", route: "/operator", target: "nav-open", titleKey: "dryRun.openNav.title", instructionKey: "dryRun.openNav.instruction", requiredEvent: "operator.open.selected" },
  { id: "open.checklist", route: "/operator/open", target: "open-checklist", titleKey: "dryRun.openChecklist.title", instructionKey: "dryRun.openChecklist.instruction", requiredEvent: "operator.open.checklist_confirmed" },
  { id: "open.temperature", route: "/operator/open", target: "open-temperature", titleKey: "dryRun.openTemp.title", instructionKey: "dryRun.openTemp.instruction", requiredEvent: "operator.temperature.entered", expectedValue: "3.2" },
  { id: "open.float", route: "/operator/open", target: "open-float", titleKey: "dryRun.openFloat.title", instructionKey: "dryRun.openFloat.instruction", requiredEvent: "operator.till.float_entered", expectedValue: "100" },
  { id: "open.confirm", route: "/operator/open", target: "open-confirm", titleKey: "dryRun.openConfirm.title", instructionKey: "dryRun.openConfirm.instruction", requiredEvent: "operator.shop.opened" },
  { id: "serve.intro", route: "/operator", target: null, titleKey: "dryRun.serveIntro.title", instructionKey: "dryRun.serveIntro.instruction" },
  { id: "serve.navigate", route: "/operator", target: "nav-serve", titleKey: "dryRun.serveNav.title", instructionKey: "dryRun.serveNav.instruction", requiredEvent: "operator.serve.selected" },
  { id: "serve.product", route: "/operator/serve", target: "serve-product-chicken", titleKey: "dryRun.serveProduct.title", instructionKey: "dryRun.serveProduct.instruction", requiredEvent: "operator.serve.product_added", expectedValue: "chicken" },
  { id: "serve.weight", route: "/operator/serve", target: "serve-weight", titleKey: "dryRun.serveWeight.title", instructionKey: "dryRun.serveWeight.instruction", requiredEvent: "operator.serve.weight_entered", expectedValue: "2" },
  { id: "serve.cash", route: "/operator/serve", target: "serve-payment-cash", titleKey: "dryRun.serveCash.title", instructionKey: "dryRun.serveCash.instruction", requiredEvent: "operator.serve.cash_selected" },
  { id: "serve.confirm", route: "/operator/serve", target: "serve-confirm", titleKey: "dryRun.serveConfirm.title", instructionKey: "dryRun.serveConfirm.instruction", requiredEvent: "operator.serve.confirmed" },
  { id: "serve.success", route: "/operator", target: null, titleKey: "dryRun.serveSuccess.title", instructionKey: "dryRun.serveSuccess.instruction" },
  { id: "stock.navigate", route: "/operator", target: "nav-stock", titleKey: "dryRun.stockNav.title", instructionKey: "dryRun.stockNav.instruction", requiredEvent: "operator.stock.selected" },
  { id: "stock.received", route: "/operator/stock", target: "stock-received", titleKey: "dryRun.stockReceived.title", instructionKey: "dryRun.stockReceived.instruction", requiredEvent: "operator.stock.delivery_selected" },
  { id: "stock.product", route: "/operator/stock", target: "stock-product-lamb", titleKey: "dryRun.stockProduct.title", instructionKey: "dryRun.stockProduct.instruction", requiredEvent: "operator.stock.product_selected", expectedValue: "lamb" },
  { id: "stock.weight", route: "/operator/stock", target: "stock-weight", titleKey: "dryRun.stockWeight.title", instructionKey: "dryRun.stockWeight.instruction", requiredEvent: "operator.stock.weight_entered", expectedValue: "12.5" },
  { id: "stock.expiry", route: "/operator/stock", target: "stock-expiry", titleKey: "dryRun.stockExpiry.title", instructionKey: "dryRun.stockExpiry.instruction", requiredEvent: "operator.stock.expiry_entered", expectedValue: "2026-08-23" },
  { id: "stock.evidence", route: "/operator/stock", target: "stock-evidence", titleKey: "dryRun.stockEvidence.title", instructionKey: "dryRun.stockEvidence.instruction", requiredEvent: "operator.stock.evidence_simulated" },
  { id: "stock.confirm", route: "/operator/stock", target: "stock-confirm", titleKey: "dryRun.stockConfirm.title", instructionKey: "dryRun.stockConfirm.instruction", requiredEvent: "operator.stock.delivery_confirmed" },
  { id: "waste.navigate", route: "/operator", target: "nav-waste", titleKey: "dryRun.wasteNav.title", instructionKey: "dryRun.wasteNav.instruction", requiredEvent: "operator.waste.selected" },
  { id: "waste.product", route: "/operator/waste", target: "waste-product-chicken", titleKey: "dryRun.wasteProduct.title", instructionKey: "dryRun.wasteProduct.instruction", requiredEvent: "operator.waste.product_selected", expectedValue: "chicken" },
  { id: "waste.weight", route: "/operator/waste", target: "waste-weight", titleKey: "dryRun.wasteWeight.title", instructionKey: "dryRun.wasteWeight.instruction", requiredEvent: "operator.waste.weight_entered", expectedValue: "0.5" },
  { id: "waste.reason", route: "/operator/waste", target: "waste-reason", titleKey: "dryRun.wasteReason.title", instructionKey: "dryRun.wasteReason.instruction", requiredEvent: "operator.waste.reason_selected", expectedValue: "damaged" },
  { id: "waste.confirm", route: "/operator/waste", target: "waste-confirm", titleKey: "dryRun.wasteConfirm.title", instructionKey: "dryRun.wasteConfirm.instruction", requiredEvent: "operator.waste.confirmed" },
  { id: "till.navigate", route: "/operator", target: "nav-till", titleKey: "dryRun.tillNav.title", instructionKey: "dryRun.tillNav.instruction", requiredEvent: "operator.till.selected" },
  { id: "till.count", route: "/operator/till", target: "till-count", titleKey: "dryRun.tillCount.title", instructionKey: "dryRun.tillCount.instruction", requiredEvent: "operator.till.count_entered", expectedValue: "114" },
  { id: "till.confirm", route: "/operator/till", target: "till-confirm", titleKey: "dryRun.tillConfirm.title", instructionKey: "dryRun.tillConfirm.instruction", requiredEvent: "operator.till.count_confirmed" },
  { id: "help.open", route: "/operator", target: "nav-help", titleKey: "dryRun.help.title", instructionKey: "dryRun.help.instruction", requiredEvent: "operator.help.opened" },
  { id: "close.navigate", route: "/operator", target: "nav-close", titleKey: "dryRun.closeNav.title", instructionKey: "dryRun.closeNav.instruction", requiredEvent: "operator.close.selected" },
  { id: "close.checklist", route: "/operator/close", target: "close-checklist", titleKey: "dryRun.closeChecklist.title", instructionKey: "dryRun.closeChecklist.instruction", requiredEvent: "operator.close.checklist_confirmed" },
  { id: "close.temperature", route: "/operator/close", target: "close-temperature", titleKey: "dryRun.closeTemp.title", instructionKey: "dryRun.closeTemp.instruction", requiredEvent: "operator.close.temperature_entered", expectedValue: "3.8" },
  { id: "close.till", route: "/operator/close", target: "close-till", titleKey: "dryRun.closeTill.title", instructionKey: "dryRun.closeTill.instruction", requiredEvent: "operator.close.till_entered", expectedValue: "114" },
  { id: "close.confirm", route: "/operator/close", target: "close-confirm", titleKey: "dryRun.closeConfirm.title", instructionKey: "dryRun.closeConfirm.instruction", requiredEvent: "operator.shop.closed" },
  { id: "complete", route: "/operator", target: null, titleKey: "dryRun.complete.title", instructionKey: "dryRun.complete.instruction" },
];
